# Generated by Django 4.1.7 on 2023-04-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
